#!/bin/bash
#move the denoise file together to update the test dataset
m=0
n=0
for file in ./AllSkeletonFiles_remove_nan_nolabel/*
do
 # echo $file
  file2=${file##*/}
  file1=${file2%.*}
 # echo $file1
 # echo $file2
 # break
  for noisefile in ./test1/*
  do
    # echo $noisefile
     noisefile1=${noisefile##*/}
    # echo $noisefile1
     noisefile2=${noisefile1%.*}
    # echo $noisefile2
     noisefile1=${noisefile1%%.*}
     #echo $noisefile1
    # break
     if [ "$file1" == "$noisefile1" ]
     then
        echo "process an noise file:$noisefile1"
        cp $noisefile ./test_no_noise/$noisefile2
        m=$[ $m + 1 ]
      # break
        continue 2
     fi
  done
  cp $file ./test_no_noise/$file2
 # break
  n=$[ $n + 1 ]
done
echo $n
echo $m
